# Generated by Django 5.0.7 on 2024-08-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
